/// Searchable USCF → chess.com player directory, bundled with the app.
///
/// Backed by `assets/data/uscf_chesscom_map.json`, generated by
/// `scripts/build_directory_assets.py` from the opponent-graph mapping in
/// `scripts/build_player_map.py`. That mapping is built from USCF-rated events
/// hosted on chess.com: if USCF player A faced opponent B in round 3, and A's
/// known chess.com account faced username Y in round 3, then B = Y. The
/// linkage is structural rather than inferred, which is why those rows carry
/// `exact` confidence.
///
/// Coverage is the limit, not precision. The directory holds a few thousand
/// players — everyone who has played a USCF-rated event on chess.com — against
/// a far larger active USCF membership. A typical entry list will partially
/// hit; misses fall through to agent-assisted resolution via the MCP bridge.
library;

import 'dart:convert';

import 'package:flutter/services.dart' show AssetBundle, rootBundle;

import '../models/player_identity.dart';
import 'player_name.dart';

const String kUscfMapAsset = 'assets/data/uscf_chesscom_map.json';
const String kTitledAsset = 'assets/data/chesscom_titled.json';

/// One row of the bundled mapping.
class DirectoryEntry {
  final String uscfId;
  final String uscfName;
  final String chesscomUsername;

  /// Confidence as recorded by the mapper (`exact`, `high`, `medium`).
  final String confidence;

  /// Which mapper strategy produced the row — `opponent_graph`,
  /// `forfeit_correlation`, `signature`, `score_position`.
  final String method;

  /// The USCF event the linkage was established from, as evidence.
  final String eventId;
  final String eventDate;

  /// Chess.com title, joined from the titled roster (null for untitled).
  final String? title;

  const DirectoryEntry({
    required this.uscfId,
    required this.uscfName,
    required this.chesscomUsername,
    required this.confidence,
    required this.method,
    this.eventId = '',
    this.eventDate = '',
    this.title,
  });

  /// Human-readable justification, surfaced verbatim in the UI and MCP output.
  String get evidence {
    final buf = StringBuffer('USCF $uscfId ($uscfName) → $chesscomUsername');
    if (method.isNotEmpty) buf.write(' via $method');
    if (eventId.isNotEmpty) {
      buf.write(' in USCF event $eventId');
      if (eventDate.isNotEmpty) buf.write(' ($eventDate)');
    }
    return buf.toString();
  }

  PlayerIdentity toIdentity() => PlayerIdentity(
    chesscomUsername: chesscomUsername,
    confidence: IdentityConfidenceLabel.fromWire(confidence),
    source: IdentitySource.uscfOnlineEvent,
    evidence: evidence,
    title: title,
  );

  Map<String, dynamic> toMap() => {
    'uscf_id': uscfId,
    'uscf_name': uscfName,
    'chesscom_username': chesscomUsername,
    'confidence': confidence,
    'method': method,
    if (eventId.isNotEmpty) 'event_id': eventId,
    if (eventDate.isNotEmpty) 'event_date': eventDate,
    if (title != null) 'title': title,
  };
}

/// A name lookup that found more than one plausible row.
class DirectoryNameMatch {
  final List<DirectoryEntry> entries;

  /// True when the name matched exactly one directory row.
  bool get isUnique => entries.length == 1;
  bool get isEmpty => entries.isEmpty;

  const DirectoryNameMatch(this.entries);
}

class PlayerDirectory {
  final Map<String, DirectoryEntry> _byUscfId;
  final Map<String, List<DirectoryEntry>> _byNameKey;
  final Map<String, DirectoryEntry> _byUsername;
  final Map<String, String> _titles;

  /// How many USCF events the bundled mapping was built from — shown in the UI
  /// so the user can tell a stale asset from a freshly backfilled one.
  final int eventsProcessed;

  const PlayerDirectory._({
    required Map<String, DirectoryEntry> byUscfId,
    required Map<String, List<DirectoryEntry>> byNameKey,
    required Map<String, DirectoryEntry> byUsername,
    required Map<String, String> titles,
    required this.eventsProcessed,
  }) : _byUscfId = byUscfId,
       _byNameKey = byNameKey,
       _byUsername = byUsername,
       _titles = titles;

  /// An empty directory — the value in use before [ensureLoaded] completes,
  /// so callers never have to null-check.
  const PlayerDirectory.empty()
    : _byUscfId = const {},
      _byNameKey = const {},
      _byUsername = const {},
      _titles = const {},
      eventsProcessed = 0;

  /// Build from already-decoded asset JSON. Tests use this directly; the app
  /// goes through [ensureLoaded].
  factory PlayerDirectory.fromJson({
    required Map<String, dynamic> mapping,
    Map<String, dynamic>? titled,
  }) {
    final titles = <String, String>{};
    final rawTitles = titled?['titles'];
    if (rawTitles is Map) {
      rawTitles.forEach((k, v) => titles['$k'.toLowerCase()] = '$v');
    }

    final byUscfId = <String, DirectoryEntry>{};
    final byNameKey = <String, List<DirectoryEntry>>{};
    final byUsername = <String, DirectoryEntry>{};

    final players = mapping['players'];
    if (players is Map) {
      players.forEach((uscfId, row) {
        if (row is! Map) return;
        final username = (row['u'] ?? '').toString();
        if (username.isEmpty) return;
        final name = (row['n'] ?? '').toString();

        final entry = DirectoryEntry(
          uscfId: '$uscfId',
          uscfName: name,
          chesscomUsername: username,
          confidence: (row['c'] ?? '').toString(),
          method: (row['m'] ?? '').toString(),
          eventId: (row['e'] ?? '').toString(),
          eventDate: (row['d'] ?? '').toString(),
          title: titles[username.toLowerCase()],
        );

        byUscfId[entry.uscfId] = entry;
        byUsername[username.toLowerCase()] = entry;
        if (name.isNotEmpty) {
          byNameKey.putIfAbsent(playerNameKey(name), () => []).add(entry);
        }
      });
    }

    return PlayerDirectory._(
      byUscfId: byUscfId,
      byNameKey: byNameKey,
      byUsername: byUsername,
      titles: titles,
      eventsProcessed: (mapping['events_processed'] as num?)?.toInt() ?? 0,
    );
  }

  // ── Singleton loading ──────────────────────────────────────────────────

  static PlayerDirectory _instance = const PlayerDirectory.empty();
  static Future<PlayerDirectory>? _loading;

  /// The loaded directory, or an empty one if [ensureLoaded] has not finished.
  static PlayerDirectory get instance => _instance;

  /// Load the bundled assets once. Idempotent and safe to call concurrently —
  /// the in-flight future is shared rather than re-fetched.
  static Future<PlayerDirectory> ensureLoaded({AssetBundle? bundle}) {
    return _loading ??= _load(bundle ?? rootBundle).then((d) {
      _instance = d;
      return d;
    });
  }

  static Future<PlayerDirectory> _load(AssetBundle bundle) async {
    final mappingRaw = await bundle.loadString(kUscfMapAsset);
    final mapping = json.decode(mappingRaw) as Map<String, dynamic>;

    Map<String, dynamic>? titled;
    try {
      titled =
          json.decode(await bundle.loadString(kTitledAsset))
              as Map<String, dynamic>;
    } catch (_) {
      // The titled roster only decorates entries with a title; a missing or
      // malformed asset must not take the whole directory down.
      titled = null;
    }

    return PlayerDirectory.fromJson(mapping: mapping, titled: titled);
  }

  /// Replace the loaded singleton. For tests and for reloading after a
  /// directory refresh.
  static void overrideInstanceForTest(PlayerDirectory directory) {
    _instance = directory;
    _loading = Future.value(directory);
  }

  // ── Lookup ─────────────────────────────────────────────────────────────

  int get playerCount => _byUscfId.length;
  int get titledCount => _titles.length;

  /// Exact lookup by USCF ID. Always prefer this — it cannot mismatch.
  DirectoryEntry? byUscfId(String uscfId) => _byUscfId[uscfId.trim()];

  /// Reverse lookup: which entrant does this chess.com account belong to?
  DirectoryEntry? byChesscomUsername(String username) =>
      _byUsername[username.trim().toLowerCase()];

  /// Chess.com title for an account, independent of the USCF mapping.
  String? titleFor(String username) => _titles[username.trim().toLowerCase()];

  /// Name lookup. Returns every row sharing the normalized `FIRST|LAST` key —
  /// two different Michael Wangs both come back, and the caller decides.
  DirectoryNameMatch byName(String name) {
    final key = playerNameKey(name);
    if (key == '|') return const DirectoryNameMatch([]);
    return DirectoryNameMatch(List.unmodifiable(_byNameKey[key] ?? const []));
  }

  /// Resolve an entrant to an identity, preferring the USCF ID.
  ///
  /// Returns null when nothing matched, and an identity carrying [alternates]
  /// when the name was ambiguous — callers must not silently take the first.
  PlayerIdentity? resolve({String? uscfId, String? name}) {
    if (uscfId != null && uscfId.trim().isNotEmpty) {
      final hit = byUscfId(uscfId);
      if (hit != null) return hit.toIdentity();
    }

    if (name != null && name.trim().isNotEmpty) {
      final match = byName(name);
      if (match.isUnique) {
        final entry = match.entries.first;
        // A name match is weaker than an ID match even when the underlying row
        // is `exact`: the row is certain, our claim that it is *this* entrant
        // is not.
        return entry.toIdentity().copyWith(
          confidence: IdentityConfidence.medium,
          evidence: '${entry.evidence} (matched on name, not USCF ID)',
        );
      }
      if (match.entries.length > 1) {
        return PlayerIdentity(
          confidence: IdentityConfidence.ambiguous,
          source: IdentitySource.uscfOnlineEvent,
          evidence:
              '${match.entries.length} directory rows share the name "$name"',
          alternates: match.entries
              .map((e) => '${e.chesscomUsername} (USCF ${e.uscfId})')
              .toList(),
        );
      }
    }

    return null;
  }

  /// Free-text search over USCF ID, name, and chess.com username.
  /// Backs the in-app searchable database.
  List<DirectoryEntry> search(String query, {int limit = 50}) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return const [];

    // An exact ID or username hit should always lead.
    final results = <DirectoryEntry>[];
    final seen = <String>{};

    void add(DirectoryEntry? e) {
      if (e == null || !seen.add(e.uscfId)) return;
      results.add(e);
    }

    add(byUscfId(q));
    add(byChesscomUsername(q));
    for (final e in byName(query).entries) {
      add(e);
    }

    if (results.length < limit) {
      for (final e in _byUscfId.values) {
        if (results.length >= limit) break;
        if (e.uscfName.toLowerCase().contains(q) ||
            e.chesscomUsername.toLowerCase().contains(q) ||
            e.uscfId.contains(q)) {
          add(e);
        }
      }
    }

    return results.take(limit).toList();
  }
}
