import 'package:chess_auto_prep/v2/chess/pgn/game_review.dart';
import 'package:chess_auto_prep/v2/chess/pgn/chapter_edit.dart';
import 'package:chess_auto_prep/v2/chess/pgn/game_tree.dart';
import 'package:chess_auto_prep/v2/engines/engine_line.dart';
import 'package:chess_auto_prep/v2/engines/engine_supervisor.dart';
import 'package:chess_auto_prep/v2/workspace/engine_analysis.dart';
import 'package:chess_auto_prep/v2/workspace/game_review.dart';
import 'package:flutter_test/flutter_test.dart';

import '../support/scripted_engine.dart';
import '../support/session_fixture.dart';

void main() {
  late SessionFixture fixture;
  late EngineAnalysis analysis;
  late ScriptedEngine engine;
  late GameReview review;
  const pgn =
      '[Event "Review"]\n[Result "*"]\n\n1. e4 {My note [%clk 0:05:00]} e5 (1... c5 {Keep me}) *';
  setUp(() async {
    fixture = await openSession(pgn);
    fixture.session.holdsEdits = true;
    engine = ScriptedEngine();
    analysis = EngineAnalysis(
      fixture.session,
      () async => const StartFailed('off'),
    );
    review = GameReview(
      session: fixture.session,
      analysis: analysis,
      launch: () async => Started(engine),
    );
  });
  tearDown(() {
    review.dispose();
    analysis.dispose();
    fixture.dispose();
  });

  test(
    'review adds evals, glyphs and PV without losing prose or variations; one undo',
    () async {
      final running = review.start();
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: const Centipawns(30), pv: ['d2d4', 'd7d5']),
      );
      engine.current.end();
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: const Centipawns(220), pv: ['c7c5', 'g1f3']),
      );
      engine.current.end();
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: const Centipawns(20), pv: ['g1f3']),
      );
      engine.current.end();
      await running;
      expect(review.problem, isNull);
      expect(review.values.map((v) => v?.cp), [30, -220, 20]);
      final tree = fixture.session.tree!;
      expect(tree.children.first.nags, contains(4));
      expect(tree.children.first.comment, contains('My note'));
      expect(tree.children.first.comment, contains('[%clk 0:05:00]'));
      expect(tree.children[1].san, 'd4');
      expect(tree.children.first.children[1].comment, contains('Keep me'));
      expect(fixture.session.hasHeldEdits, isTrue);
      expect(fixture.onDisk, pgn);
      expect(engine.quitCalled, isTrue);
      await fixture.session.undo();
      expect(fixture.session.tree!.children.length, 1);
      expect(fixture.session.tree!.rootComment, isNull);
    },
  );

  test(
    'an edit during analysis cancels; late values cannot overwrite it',
    () async {
      final running = review.start();
      await pumpEventQueue();
      fixture.session.setComment(const NodePath.root(), 'New note');
      expect(engine.current.stopped, isTrue);
      engine.current.emit(line(depth: 14));
      engine.current.end();
      await running;
      expect(fixture.session.tree!.rootComment, 'New note');
      expect(
        fixture.session.tree!.children.first.comment,
        isNot(contains('[%eval')),
      );
      expect(engine.quitCalled, isTrue);
    },
  );

  test('stop and incomplete engine output leave source untouched', () async {
    final running = review.start();
    await pumpEventQueue();
    engine.current.emit(line(depth: 4));
    engine.current.end();
    await running;
    expect(review.problem, contains('could not finish'));
    expect(fixture.session.hasHeldEdits, isFalse);
    expect(fixture.onDisk, pgn);
  });

  test('reanalysis replaces only the glyphs generated by review', () {
    final marked =
        annotateGame(fixture.session.chapter!, const [
              ReviewValue(0, '0.00', []),
              ReviewValue(-250, '-2.50', []),
              ReviewValue(-250, '-2.50', []),
            ])
            as ChapterEdited;
    expect(marked.chapter.tree.children.first.nags, contains(4));
    final cleared =
        annotateGame(marked.chapter, const [
              ReviewValue(0, '0.00', []),
              ReviewValue(0, '0.00', []),
              ReviewValue(0, '0.00', []),
            ])
            as ChapterEdited;
    expect(cleared.chapter.tree.children.first.nags, isEmpty);
    expect(cleared.chapter.tree.children.first.comment, contains('My note'));
  });

  test('stored eval supports depth and signed mate', () {
    expect(storedReviewValue('text [%eval -0.34,18]')?.cp, -34);
    expect(storedReviewValue('[%eval #-3]')?.cp, -10000);
    expect(storedReviewValue('no score'), isNull);
  });
}
