/// A local study: one PGN file holding multiple annotated games
/// ("chapters"), each an editable [MoveTree] — think Lichess studies,
/// stored on disk.
///
/// The on-disk chapter format *is* the Lichess study export format, so a
/// study downloaded from Lichess and one written here look the same and
/// either can be re-imported by the other:
///
/// ```
/// [Event "Study name: Chapter name"]
/// [StudyName "Study name"]
/// [ChapterName "Chapter name"]
/// [Orientation "black"]
/// [FEN "…"] [SetUp "1"]          — only for a custom start position
/// ```
///
/// Round-trip contract: every other header is preserved per chapter
/// (`Result`, `ECO`, `Annotator`, `ChapterURL`, …); the ones above are owned
/// by this model and regenerated on save; and the chapter's own opening note
/// — the prose a study puts before move 1 — is kept in [StudyChapter.intro].
///
/// The contract is not cosmetic. Editing anywhere in a study (playing a move
/// counts) rewrites the *whole file* from this model, so whatever the model
/// cannot hold is deleted from the reader's study on the next autosave.
library;

import 'package:dartchess/dartchess.dart' show Side;

import '../constants/chess_constants.dart';
import '../services/pgn_parsing_service.dart'
    show splitPgnIntoGames, extractHeaders, stripBom;
import '../utils/fen_utils.dart' show isWhiteToMove;
import 'move_tree.dart';

class StudyChapter {
  String name;

  /// Which side the board shows at the bottom when the chapter opens.
  Side orientation;

  /// Original PGN headers minus the ones this model owns (see the library
  /// doc).  Preserved so tags like ECO or Annotator survive a round-trip.
  final Map<String, String> headers;

  final MoveTree tree;

  /// The chapter's own note, written before its first move — where a Lichess
  /// study chapter's introduction lives. Empty when there is none.
  ///
  /// One home, not two: the note is a comment on the starting position, so it
  /// lives in the tree with every other comment and is written out by
  /// [MoveTree.toPgnMoveText]. A second copy here would be written twice and
  /// would drift the moment the editor set a comment on the empty path.
  String get intro => tree.rootComment ?? '';
  set intro(String value) => tree.rootComment = value;

  /// Headers regenerated by [toPgn]; never kept in [headers].
  static const ownedHeaders = {
    'Event',
    'StudyName',
    'ChapterName',
    'Orientation',
    'FEN',
    'SetUp',
  };

  StudyChapter({
    required String name,
    Map<String, String>? headers,
    MoveTree? tree,
    String? startingFen,
    Side? orientation,
    String intro = '',
  }) : this._(
         name,
         headers,
         tree ?? MoveTree(startingFen: startingFen),
         orientation,
         intro,
       );

  StudyChapter._(
    this.name,
    Map<String, String>? rawHeaders,
    this.tree,
    Side? orientation,
    String intro,
  ) : headers = _withoutOwned(rawHeaders),
      orientation =
          orientation ?? _orientationFromHeaders(rawHeaders, tree.startingFen) {
    // Only when the caller supplied one: a tree parsed from PGN already
    // carries the note, and an empty argument must not erase it.
    if (intro.trim().isNotEmpty) this.intro = intro;
  }

  /// One chapter, parsed from the text of one game — the single place that
  /// decides what a chapter keeps, so a caller cannot build one that quietly
  /// keeps less.
  factory StudyChapter.fromGameText(
    String gameText, {
    String? name,
    String? studyName,
  }) {
    final headers = extractHeaders(gameText);
    return StudyChapter(
      name:
          name ??
          nameFromHeaders(headers, fallback: 'Chapter', studyName: studyName),
      headers: headers,
      tree: MoveTree.fromPgn(gameText),
    );
  }

  /// Result header token used to terminate the movetext ("*" when absent).
  String get result => headers['Result'] ?? '*';

  /// The chapter as one PGN game.  [studyName] goes into the Lichess-style
  /// `[Event "Study: Chapter"]` and `[StudyName]` tags; omit it for a chapter
  /// that is not (yet) part of a named study.
  String toPgn({String? studyName}) {
    final study = studyName?.trim();
    final lines = <String>[];
    final event = study == null || study.isEmpty ? name : '$study: $name';
    lines.add('[Event "${_escape(event)}"]');
    if (study != null && study.isNotEmpty) {
      lines.add('[StudyName "${_escape(study)}"]');
    }
    lines.add('[ChapterName "${_escape(name)}"]');
    for (final entry in headers.entries) {
      if (ownedHeaders.contains(entry.key)) continue;
      lines.add('[${entry.key} "${_escape(entry.value)}"]');
    }
    lines.add('[Orientation "${orientation.name}"]');
    if (tree.startingFen != kStandardStartFen) {
      lines.add('[FEN "${tree.startingFen}"]');
      lines.add('[SetUp "1"]');
    }

    final moveText = tree.toPgnMoveText();
    final body = moveText.isEmpty ? result : '$moveText $result';
    return '${lines.join('\n')}\n\n$body\n';
  }

  /// The chapter name a PGN game's headers describe.
  ///
  /// `ChapterName` wins; failing that, `Event` with a leading
  /// `"<study name>: "` stripped (what Lichess exports carry and what older
  /// files written here used verbatim); failing that, the players; failing
  /// that, [fallback].
  static String nameFromHeaders(
    Map<String, String> headers, {
    required String fallback,
    String? studyName,
  }) {
    String? tag(String key) {
      final value = headers[key]?.trim();
      return value == null || value.isEmpty || value == '?' ? null : value;
    }

    final chapterName = tag('ChapterName');
    if (chapterName != null) return chapterName;
    final event = tag('Event');
    if (event != null) {
      for (final prefix in {tag('StudyName'), studyName}) {
        if (prefix == null) continue;
        final head = '$prefix: ';
        if (event.startsWith(head) && event.length > head.length) {
          return event.substring(head.length).trim();
        }
      }
      return event;
    }
    final white = tag('White');
    final black = tag('Black');
    if (white != null && black != null) return '$white - $black';
    return white ?? black ?? fallback;
  }

  static Map<String, String> _withoutOwned(Map<String, String>? headers) {
    if (headers == null) return {};
    return {
      for (final entry in headers.entries)
        if (!ownedHeaders.contains(entry.key)) entry.key: entry.value,
    };
  }

  /// `[Orientation]` when the file says; otherwise a chapter from a set-up
  /// position faces the side to move (a puzzle is solved from its solver's
  /// side) and a chapter from the initial position faces White.
  static Side _orientationFromHeaders(
    Map<String, String>? headers,
    String startingFen,
  ) {
    switch (headers?['Orientation']?.trim().toLowerCase()) {
      case 'white':
        return Side.white;
      case 'black':
        return Side.black;
    }
    if (startingFen == kStandardStartFen) return Side.white;
    return isWhiteToMove(startingFen) ? Side.white : Side.black;
  }

  static String _escape(String value) =>
      value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
}

class StudyDocument {
  /// Absolute path of the backing `.pgn` file (`null` until first save).
  String? filePath;

  /// Display name (the file's basename).
  String name;

  final List<StudyChapter> chapters;

  StudyDocument({
    this.filePath,
    required this.name,
    List<StudyChapter>? chapters,
  }) : chapters = chapters ?? [];

  /// A new study with one empty chapter.
  factory StudyDocument.fresh(String name) => StudyDocument(
    name: name,
    chapters: [StudyChapter(name: 'Chapter 1')],
  );

  factory StudyDocument.fromPgn(
    String content, {
    required String name,
    String? filePath,
  }) {
    final chapters = <StudyChapter>[];
    final games = splitPgnIntoGames(stripBom(content));
    for (int i = 0; i < games.length; i++) {
      final gameText = games[i];
      final headers = extractHeaders(gameText);
      // MoveTree.fromPgn reads the [FEN] header itself.
      chapters.add(
        StudyChapter.fromGameText(
          gameText,
          name: StudyChapter.nameFromHeaders(
            headers,
            fallback: 'Chapter ${i + 1}',
            studyName: name,
          ),
        ),
      );
    }
    if (chapters.isEmpty) {
      chapters.add(StudyChapter(name: 'Chapter 1'));
    }
    return StudyDocument(name: name, filePath: filePath, chapters: chapters);
  }

  String toPgn() => chapters.map((c) => c.toPgn(studyName: name)).join('\n');
}
