import 'package:chess_auto_prep/chess/pgn/chapter.dart';
import 'package:chess_auto_prep/chess/pgn/comment_edits.dart';
import 'package:chess_auto_prep/chess/pgn/game_review.dart';
import 'package:chess_auto_prep/chess/pgn/chapter_edit.dart';
import 'package:chess_auto_prep/chess/pgn/game_tree.dart';
import 'package:chess_auto_prep/chess/pgn/move_text.dart';
import 'package:chess_auto_prep/chess/pgn/rewrite_gate.dart';
import 'package:chess_auto_prep/chess/pgn/tree_edit.dart';
import 'package:chess_auto_prep/workspace/chapter_commands.dart';
import 'package:dartchess/dartchess.dart' show Move;
import 'package:chess_auto_prep/engines/engine_line.dart';
import 'package:chess_auto_prep/engines/engine_supervisor.dart';
import 'package:chess_auto_prep/workspace/engine_analysis.dart';
import 'package:chess_auto_prep/workspace/engine_jobs.dart';
import 'package:chess_auto_prep/workspace/game_review.dart';
import 'package:flutter_test/flutter_test.dart';

import '../support/scripted_engine.dart';
import '../support/session_fixture.dart';

/// [chapter] with [uci] played after the node at [at] of its one game.
Chapter _played(Chapter chapter, NodePath at, String uci) {
  final line = chapter.lines.single;
  final tree = line.tree!;
  final node = moveNode(tree.fenAt(at), Move.parse(uci)!)!;
  final written = rewritten(line, withChildAdded(tree, at, node));
  return withLines(chapter, [(written as LineRewritten).line]);
}

void main() {
  late SessionFixture fixture;
  late EngineAnalysis analysis;
  late EngineJobs jobs;
  late ScriptedEngine engine;
  late GameReview review;
  const pgn =
      '[Event "Review"]\n[Result "*"]\n\n1. e4 {My note [%clk 0:05:00]} e5 (1... c5 {Keep me}) *';
  setUp(() async {
    fixture = await openSession(pgn);
    fixture.session.holdsEdits = true;
    engine = ScriptedEngine();
    analysis = EngineAnalysis(
      fixture.session,
      () async => const StartFailed('off'),
    );
    jobs = EngineJobs(analysis);
    review = GameReview(
      session: fixture.session,
      jobs: jobs,
      launch: () async => Started(engine),
    );
  });
  tearDown(() {
    review.dispose();
    jobs.dispose();
    analysis.dispose();
    fixture.dispose();
  });

  test(
    'review adds evals, glyphs and PV without losing prose or variations; one undo',
    () async {
      final running = review.start();
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: const Centipawns(30), pv: ['d2d4', 'd7d5']),
      );
      engine.current.end();
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: const Centipawns(220), pv: ['c7c5', 'g1f3']),
      );
      engine.current.end();
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: const Centipawns(20), pv: ['g1f3']),
      );
      engine.current.end();
      await running;
      expect(review.problem, isNull);
      expect(review.values.map((v) => v?.cp), [30, -220, 20]);
      final tree = fixture.session.tree!;
      expect(tree.children.first.nags, contains(4));
      expect(tree.children.first.comment, contains('My note'));
      expect(tree.children.first.comment, contains('[%clk 0:05:00]'));
      expect(tree.children[1].san, 'd4');
      expect(tree.children.first.children[1].comment, contains('Keep me'));
      expect(fixture.session.hasHeldEdits, isTrue);
      expect(fixture.onDisk, pgn);
      expect(engine.quitCalled, isTrue);
      await fixture.session.undo();
      expect(fixture.session.tree!.children.length, 1);
      expect(fixture.session.tree!.rootComment, isNull);
    },
  );

  test(
    'an edit during analysis cancels; late values cannot overwrite it',
    () async {
      final running = review.start();
      await pumpEventQueue();
      fixture.session.setComment(const NodePath.root(), 'New note');
      expect(engine.current.stopped, isTrue);
      engine.current.emit(line(depth: 14));
      engine.current.end();
      await running;
      expect(fixture.session.tree!.rootComment, 'New note');
      expect(
        fixture.session.tree!.children.first.comment,
        isNot(contains('[%eval')),
      );
      expect(engine.quitCalled, isTrue);
    },
  );

  test('stop and incomplete engine output leave source untouched', () async {
    final running = review.start();
    await pumpEventQueue();
    engine.current.emit(line(depth: 4));
    engine.current.end();
    await running;
    expect(review.problem, contains('could not finish'));
    expect(fixture.session.hasHeldEdits, isFalse);
    expect(fixture.onDisk, pgn);
  });

  test('reanalysis replaces only the glyphs generated by review', () {
    final marked =
        annotateGame(fixture.session.chapter!, const [
              ReviewValue(0, '0.00', []),
              ReviewValue(-250, '-2.50', []),
              ReviewValue(-250, '-2.50', []),
            ])
            as ChapterEdited;
    expect(marked.chapter.tree.children.first.nags, contains(4));
    final cleared =
        annotateGame(marked.chapter, const [
              ReviewValue(0, '0.00', []),
              ReviewValue(0, '0.00', []),
              ReviewValue(0, '0.00', []),
            ])
            as ChapterEdited;
    expect(cleared.chapter.tree.children.first.nags, isEmpty);
    expect(cleared.chapter.tree.children.first.comment, contains('My note'));
  });

  test('stored eval supports depth and signed mate', () {
    expect(storedReviewValue('text [%eval -0.34,18]')?.cp, -34);
    expect(storedReviewValue('[%eval #-3]')?.cp, -10000);
    expect(storedReviewValue('no score'), isNull);
  });

  test('removing the review gives back the game as the file had it', () {
    final before = writeMoveText(fixture.session.tree!, terminator: '*');
    final marked =
        annotateGame(fixture.session.chapter!, const [
              ReviewValue(30, '0.30', ['d2d4', 'd7d5']),
              ReviewValue(-220, '-2.20', ['c7c5', 'g1f3']),
              ReviewValue(20, '0.20', ['g1f3']),
            ])
            as ChapterEdited;
    final tree = marked.chapter.tree;
    expect(hasReview(tree), isTrue);
    expect(tree.children.first.comment, startsWith('Blunder. d4 was best.'));
    expect(tree.children, hasLength(2));
    final removed = removeReview(marked.chapter) as ChapterEdited;
    expect(hasReview(removed.chapter.tree), isFalse);
    expect(writeMoveText(removed.chapter.tree, terminator: '*'), before);
    expect(removeReview(removed.chapter), isA<ChapterUnchanged>());
  });

  // The review adds 1. d4 d5 as the alternative to 1. e4, at path [1].
  const reviewed = [
    ReviewValue(30, '0.30', ['d2d4', 'd7d5']),
    ReviewValue(-220, '-2.20', ['c7c5', 'g1f3']),
    ReviewValue(20, '0.20', ['g1f3']),
  ];

  test('a move the user adds inside a review line survives removal', () {
    final marked =
        annotateGame(fixture.session.chapter!, reviewed) as ChapterEdited;
    expect(marked.chapter.tree.children[1].san, 'd4');
    final extended = _played(marked.chapter, NodePath.of([1, 0]), 'c2c4');
    final removed = removeReview(extended) as ChapterEdited;
    final tree = removed.chapter.tree;
    expect(hasReview(tree), isFalse);
    expect(tree.nodeAt(NodePath.of([1]))?.san, 'd4');
    expect(tree.nodeAt(NodePath.of([1]))?.comment, isNull);
    expect(tree.nodeAt(NodePath.of([1, 0]))?.san, 'd5');
    expect(tree.nodeAt(NodePath.of([1, 0, 0]))?.san, 'c4');
  });

  test("a note on the review line's first move survives removal", () {
    final marked =
        annotateGame(fixture.session.chapter!, reviewed) as ChapterEdited;
    final noted =
        setComment(marked.chapter, at: NodePath.of([1]), text: 'plan: Rad1')
            as CommentWritten;
    final removed = removeReview(noted.chapter) as ChapterEdited;
    final head = removed.chapter.tree.nodeAt(NodePath.of([1]));
    expect(head?.san, 'd4');
    expect(head?.comment, 'plan: Rad1');
    expect(hasReview(removed.chapter.tree), isFalse);
  });

  test("re-reviewing keeps the user's additions once", () {
    final marked =
        annotateGame(fixture.session.chapter!, reviewed) as ChapterEdited;
    final extended = _played(marked.chapter, NodePath.of([1, 0]), 'c2c4');
    final again = annotateGame(extended, reviewed) as ChapterEdited;
    final tree = again.chapter.tree;
    expect(tree.children.where((n) => n.san == 'd4'), hasLength(1));
    expect(tree.nodeAt(NodePath.of([1, 0]))?.children.single.san, 'c4');
  });

  test('a review line with the old bare marker is still taken out', () async {
    final legacy = await openSession(
      '[Event "E"]\n[Result "*"]\n\n'
      '1. e4 e5 (1... d5 {[%cap_review_line]} 2. exd5) *',
    );
    addTearDown(legacy.dispose);
    final removed = removeReview(legacy.session.chapter!) as ChapterEdited;
    expect(writeMoveText(removed.chapter.tree, terminator: '*'), '1. e4 e5 *');
  });

  test('an evaluation the file had is kept and survives removal', () async {
    final withEval = await openSession(
      '[Event "E"]\n[Result "*"]\n\n1. e4 {[%eval 0.25]} *',
    );
    addTearDown(withEval.dispose);
    final marked =
        annotateGame(withEval.session.chapter!, const [
              ReviewValue(20, '0.20', []),
              ReviewValue(31, '0.31', []),
            ])
            as ChapterEdited;
    expect(marked.chapter.tree.children.first.comment, '[%eval 0.25]');
    final removed = removeReview(marked.chapter) as ChapterEdited;
    expect(removed.chapter.tree.children.first.comment, '[%eval 0.25]');
  });

  test('the switch takes the review out and puts it back', () async {
    final running = review.start();
    for (final cp in [30, 220, 20]) {
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: Centipawns(cp), pv: const ['g1f3']),
      );
      engine.current.end();
    }
    await running;
    expect(review.annotated, isTrue);
    review.setAnnotate(false);
    expect(review.annotated, isFalse);
    expect(review.values.map((v) => v?.cp), [30, -220, 20]);
    expect(review.canAnnotate, isTrue);
    review.setAnnotate(true);
    expect(review.annotated, isTrue);
    expect(fixture.session.tree!.children.first.nags, contains(4));
  });

  test('a saved review is not put back onto a changed main line', () async {
    final running = review.start();
    for (final cp in [30, 220, 20]) {
      await pumpEventQueue();
      engine.current.emit(
        line(depth: 14, score: Centipawns(cp), pv: const ['g1f3']),
      );
      engine.current.end();
    }
    await running;
    review.setAnnotate(false);
    // 1... e5 goes; 1... c5 becomes the main line, as long as before.
    expect(deleteFrom(fixture.session, NodePath.of([0, 0])), isNull);
    expect(fixture.session.tree!.nodeAt(NodePath.of([0, 0]))?.san, 'c5');
    expect(review.positions, 3);
    expect(review.values, everyElement(isNull));
    review.setAnnotate(true);
    final tree = fixture.session.tree!;
    expect(hasReview(tree), isFalse);
    final last = tree.nodeAt(NodePath.of([0, 0]))!;
    expect(last.comment ?? '', isNot(contains('[%eval')));
    expect(last.nags.where((n) => n == 2 || n == 4 || n == 6), isEmpty);
  });
}
