import 'dart:math' as math;

import 'package:flutter/material.dart';

import '../../models/tactics_position.dart';
import '../../services/tactics_engine.dart';
import '../../theme/app_colors.dart';
import '../../theme/app_text_styles.dart';
import '../../utils/pgn_comment_utils.dart' show filterDisplayComment;
import '../clickable_move_line.dart';
import '../shortcut_tooltip.dart';

/// Notes generated by imports before July 2026 read "Blunder. Win chance
/// dropped from 69.2% to 48.9% (0.4%). Best was Qf3." — broken twice at
/// display time: [filterDisplayComment]'s Lichess-classification stripper
/// eats "Blunder. … 69." (stopping at the decimal point, leaving nonsense
/// like "2% to 48.9%"), the parenthesized delta is in winning-chance units,
/// and nobody thinks in win percentages anyway. Rewritten for display to the
/// terse current format ("+2.2 → -0.1, Qf3 +2.2"), recovering approximate
/// evals by inverting the Lichess win-chance formula; storage stays raw.
final _legacyPercentNoteRe = RegExp(
  r'^(?:Blunder|Mistake|Inaccuracy)\. Win chance dropped from '
  r'(\d+(?:\.\d+)?)% to (\d+(?:\.\d+)?)% \(-?\d+(?:\.\d+)?%\)\.'
  r'(?: Best was (\S+?)\.?)?$',
);

/// One short-lived intermediate format also in the wild ("Blunder: h5
/// dropped your eval from +0.5 to -2.1 (win chance 55% → 21%). Best was
/// Qf3.") — same rewrite, evals already present.
final _legacyVerboseNoteRe = RegExp(
  r'^(?:Blunder|Mistake|Inaccuracy): (\S+) dropped your eval from '
  r'(\S+) to (\S+) \(win chance [^)]*\)\. Best was (\S+?)\.?$',
);

/// Inverse of the Lichess winning-chances formula: win percent → eval in
/// pawns ("+2.2"). The forward formula caps centipawns at ±1000, so the
/// recovered eval saturates at ±10.0.
String _evalFromWinPercent(double winPercent) {
  const multiplier = -0.00368208; // matches TacticsImportService
  final wc = ((winPercent - 50) / 50).clamp(-0.999, 0.999);
  final cp = math.log((1 - wc) / (1 + wc)) / multiplier;
  final pawns = (cp / 100).clamp(-10.0, 10.0);
  return '${pawns >= 0 ? '+' : ''}${pawns.toStringAsFixed(1)}';
}

/// The tactic note ready for display: legacy generated notes rewritten to
/// the terse eval format, engine tokens and scraped-PGN noise stripped.
String displayTacticsNote(String raw) {
  final trimmed = raw.trim();
  final percent = _legacyPercentNoteRe.firstMatch(trimmed);
  if (percent != null) {
    final before = _evalFromWinPercent(double.parse(percent.group(1)!));
    final after = _evalFromWinPercent(double.parse(percent.group(2)!));
    final best = percent.group(3);
    raw = best != null ? '$before → $after, $best $before' : '$before → $after';
  } else {
    final verbose = _legacyVerboseNoteRe.firstMatch(trimmed);
    if (verbose != null) {
      raw =
          '${verbose.group(1)} ${verbose.group(2)} → ${verbose.group(3)}, '
          '${verbose.group(4)} ${verbose.group(2)}';
    }
  }
  return filterDisplayComment(raw);
}

/// Puzzle-solving controls shown during an active tactics session.
class TacticsTrainingPanel extends StatelessWidget {
  const TacticsTrainingPanel({
    super.key,
    required this.position,
    required this.engine,
    required this.currentMoveIndex,
    required this.positionSolved,
    required this.showSolution,
    required this.isAtStartingPosition,
    required this.feedback,
    required this.autoAdvance,
    required this.onToggleSolution,
    required this.onAnalyze,
    required this.onResetAnalysis,
    this.onPreviousPosition,
    this.onSkipPosition,
    this.isLastSessionPuzzle = false,
    required this.onAutoAdvanceChanged,
    required this.onCopyFen,
    this.onBack,
    this.backTooltip = 'Back',
    this.onEdit,
    required this.onSetRating,
    this.solutionSanMoves = const [],
    this.solutionStartPly = 0,
    this.activeSolutionMoveIndex,
    this.onSolutionMoveTapped,
  });

  final TacticsPosition position;
  final TacticsEngine engine;
  final int currentMoveIndex;
  final bool positionSolved;
  final bool showSolution;
  final bool isAtStartingPosition;
  final String feedback;
  final bool autoAdvance;
  final VoidCallback onToggleSolution;
  final VoidCallback onAnalyze;
  final VoidCallback onResetAnalysis;

  /// Null grays the button out — the first puzzle has no "previous".
  final VoidCallback? onPreviousPosition;

  /// Null grays the button out — the last item of a browse walk has no
  /// "next". (In a session Next stays live on the last puzzle; it finishes
  /// the session, see [isLastSessionPuzzle].)
  final VoidCallback? onSkipPosition;

  /// Relabels Skip/Next to "Finish": pressing it ends the session and shows
  /// the recap instead of loading another puzzle.
  final bool isLastSessionPuzzle;
  final ValueChanged<bool> onAutoAdvanceChanged;
  final VoidCallback onCopyFen;

  /// Leaves the current puzzle: back to the browse list for browse-launched
  /// play, or ends the session and returns to the home panel. Hidden when
  /// null.
  final VoidCallback? onBack;

  /// Tooltip for the header back arrow (varies with where back leads).
  final String backTooltip;

  /// Opens the edit dialog for this tactic. Hidden when null (external sets,
  /// or the unsolved head of a session where editing would reveal the answer).
  final VoidCallback? onEdit;
  final ValueChanged<int> onSetRating;
  final List<String> solutionSanMoves;
  final int solutionStartPly;
  final int? activeSolutionMoveIndex;
  final void Function(List<String> sanMoves, int clickedIndex)?
  onSolutionMoveTapped;

  bool get _showRating => !autoAdvance && (positionSolved || showSolution);

  bool get _useNextLabel => positionSolved || showSolution;

  String get _nextLabel {
    if (isLastSessionPuzzle) return 'Finish';
    return _useNextLabel ? 'Next' : 'Skip';
  }

  String get _nextDescription {
    if (onSkipPosition == null) return 'Already at the last position';
    if (isLastSessionPuzzle) return 'Finish the session';
    return _useNextLabel ? 'Next position' : 'Skip position';
  }

  /// The puzzle's note (annotation / mistake analysis) is the flashcard
  /// "back": revealed once the puzzle is solved or the solution shown.
  bool get _showNote =>
      (positionSolved || showSolution) &&
      displayTacticsNote(position.mistakeAnalysis).isNotEmpty;

  Color _feedbackColor() {
    if (feedback.contains('Correct')) return AppColors.success;
    return AppColors.danger;
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        TacticsPositionInfo(
          position: position,
          engine: engine,
          onBack: onBack,
          backTooltip: backTooltip,
          onEdit: onEdit,
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            Expanded(
              child: shortcutTooltip(
                description: showSolution ? 'Hide solution' : 'Show solution',
                shortcut: 'Space',
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: onToggleSolution,
                    child: Text(
                      showSolution ? 'Hide Solution' : 'Show Solution',
                    ),
                  ),
                ),
              ),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: isAtStartingPosition
                  ? shortcutTooltip(
                      description: 'Analyze',
                      shortcut: 'A',
                      child: SizedBox(
                        width: double.infinity,
                        child: ElevatedButton(
                          onPressed: onAnalyze,
                          child: const Text('Analyze'),
                        ),
                      ),
                    )
                  : shortcutTooltip(
                      description: 'Reset analysis',
                      shortcut: 'A',
                      child: SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          onPressed: onResetAnalysis,
                          icon: const Icon(Icons.refresh, size: 16),
                          label: const Text('Reset'),
                        ),
                      ),
                    ),
            ),
          ],
        ),
        const SizedBox(height: 8),
        Row(
          children: [
            Expanded(
              child: shortcutTooltip(
                description: onPreviousPosition != null
                    ? 'Previous position'
                    : 'Already at the first position',
                shortcut: 'P or ↑',
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: onPreviousPosition,
                    child: const Text('Previous'),
                  ),
                ),
              ),
            ),
            const SizedBox(width: 8),
            Expanded(
              child: shortcutTooltip(
                description: _nextDescription,
                shortcut: 'N or ↓',
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    onPressed: onSkipPosition,
                    child: Text(_nextLabel),
                  ),
                ),
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        ShortcutTooltip(
          description: 'Toggle auto-advance to next position',
          shortcut: 'J',
          child: CheckboxListTile(
            value: autoAdvance,
            onChanged: (value) => onAutoAdvanceChanged(value ?? true),
            title: const Text('Auto-advance to next position'),
            contentPadding: EdgeInsets.zero,
          ),
        ),
        // Everything below is the flashcard "back": it reveals downward as the
        // puzzle is solved or the solution is shown. The fixed controls above
        // never move, so revealing this content can't bounce the buttons. Each
        // block leads with its own gap for uniform spacing regardless of which
        // ones are visible.
        if (feedback.isNotEmpty) ...[
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: _feedbackColor().withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: _feedbackColor()),
            ),
            child: Text(
              feedback,
              style: TextStyle(
                fontWeight: FontWeight.bold,
                color: _feedbackColor(),
                fontSize: 16,
              ),
            ),
          ),
        ],
        if (_showNote) ...[
          const SizedBox(height: 8),
          _NoteCard(note: position.mistakeAnalysis),
        ],
        _buildPlayedMoves(),
        if (showSolution) ...[
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              border: Border.all(color: AppColors.onSurfaceMuted),
              borderRadius: BorderRadius.circular(4),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(child: _buildSolutionLine(context)),
                    const SizedBox(width: 8),
                    ElevatedButton(
                      onPressed: onCopyFen,
                      child: const Text('Copy FEN'),
                    ),
                  ],
                ),
                if (solutionSanMoves.isEmpty &&
                    position.correctLine.isEmpty) ...[
                  const SizedBox(height: 4),
                  const Text(
                    'No solution available',
                    style: AppTextStyles.muted,
                  ),
                ],
              ],
            ),
          ),
        ],
        if (_showRating) ...[
          const SizedBox(height: 12),
          _TacticsStarRating(rating: position.rating, onSetRating: onSetRating),
        ],
      ],
    );
  }

  Widget _buildPlayedMoves() {
    if (currentMoveIndex == 0) return const SizedBox.shrink();
    final totalUserMoves = engine.userMoveCount(position);
    if (totalUserMoves <= 1) return const SizedBox.shrink();

    final played = position.correctLine.sublist(
      0,
      currentMoveIndex.clamp(0, position.correctLine.length),
    );
    if (played.isEmpty) return const SizedBox.shrink();

    final buf = StringBuffer();
    var moveNum = (solutionStartPly ~/ 2) + 1;
    var isWhite = solutionStartPly % 2 == 0;

    for (int i = 0; i < played.length; i++) {
      if (isWhite) {
        buf.write('$moveNum. ');
      } else if (i == 0) {
        buf.write('$moveNum... ');
      }
      buf.write(played[i]);
      if (!isWhite) moveNum++;
      isWhite = !isWhite;
      if (i < played.length - 1) buf.write(' ');
    }

    return Padding(
      // Leading gap (matching the other reveal blocks) so spacing stays even
      // whether or not the solution/rating below it are visible.
      padding: const EdgeInsets.only(top: 8),
      child: Text(
        buf.toString(),
        style: const TextStyle(fontSize: 14, color: AppColors.onSurfaceSoft),
      ),
    );
  }

  Widget _buildSolutionLine(BuildContext context) {
    final san = solutionSanMoves;
    if (san.isEmpty) {
      final fallback = engine.getSolution(position, fromIndex: 0);
      if (fallback == 'No solution available') {
        return Text(fallback, style: AppTextStyles.muted);
      }
      return Text(fallback, style: AppTextStyles.mono);
    }

    final trainablePlies = position.correctLine.length;
    final highlightIndex =
        activeSolutionMoveIndex ??
        (currentMoveIndex < trainablePlies ? currentMoveIndex : null);

    return ClickableMoveLineWidget(
      key: const Key('tactic-solution-line'),
      sanMoves: san,
      startPly: solutionStartPly,
      maxMoves: san.length,
      singleLine: false,
      fontSize: 14,
      movePadding: const EdgeInsets.symmetric(horizontal: 4, vertical: 2),
      activeMoveIndex: highlightIndex,
      onMoveTapped: onSolutionMoveTapped != null
          ? (idx) => onSolutionMoveTapped!(san, idx)
          : null,
    );
  }
}

/// The puzzle's annotation, shown after solving (flashcard back).
class _NoteCard extends StatelessWidget {
  const _NoteCard({required this.note});

  final String note;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: theme.colorScheme.surfaceContainerHighest.withValues(alpha: 0.5),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: theme.colorScheme.outlineVariant),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            Icons.sticky_note_2_outlined,
            size: 18,
            color: theme.colorScheme.onSurfaceVariant,
          ),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              // Notes come from imports or scraped PGN comments — rewrite
              // legacy generated text, strip engine tokens, and collapse
              // stray double spaces into readable prose.
              displayTacticsNote(note),
              style: theme.textTheme.bodyMedium,
            ),
          ),
        ],
      ),
    );
  }
}

/// Compact 1-5 star rating row for tactic quality.
class _TacticsStarRating extends StatelessWidget {
  const _TacticsStarRating({required this.rating, required this.onSetRating});

  final int rating;
  final ValueChanged<int> onSetRating;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        const Text(
          'Rate:',
          style: TextStyle(fontSize: 13, color: AppColors.onSurfaceSoft),
        ),
        const SizedBox(width: 8),
        for (int star = 1; star <= 5; star++)
          Tooltip(
            message: 'Rate $star star${star > 1 ? 's' : ''}',
            child: GestureDetector(
              onTap: () => onSetRating(rating == star ? 0 : star),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 2),
                child: Icon(
                  star <= rating ? Icons.star : Icons.star_border,
                  size: 24,
                  color: star <= rating
                      ? AppColors.starAccent
                      : AppColors.starEmpty,
                ),
              ),
            ),
          ),
        if (rating > 0)
          Padding(
            padding: const EdgeInsets.only(left: 8),
            child: Text(
              rating == 1 ? '(hidden from training)' : '',
              style: const TextStyle(
                fontSize: 11,
                color: AppColors.onSurfaceMuted,
              ),
            ),
          ),
      ],
    );
  }
}

/// Context and game info for the current tactic position.
class TacticsPositionInfo extends StatelessWidget {
  const TacticsPositionInfo({
    super.key,
    required this.position,
    required this.engine,
    this.onBack,
    this.backTooltip = 'Back',
    this.onEdit,
  });

  final TacticsPosition position;
  final TacticsEngine engine;

  /// Leaves the current puzzle (browse list or home panel). Hidden when null.
  final VoidCallback? onBack;

  /// Tooltip for the back arrow.
  final String backTooltip;

  /// Opens the edit dialog for this tactic. Hidden when null.
  final VoidCallback? onEdit;

  @override
  Widget build(BuildContext context) {
    final pos = position;
    final moveCount = math.max(1, engine.userMoveCount(pos));

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            if (onBack != null)
              IconButton(
                onPressed: onBack,
                icon: const Icon(Icons.arrow_back, size: 18),
                tooltip: backTooltip,
                visualDensity: VisualDensity.compact,
                constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
                padding: EdgeInsets.zero,
              ),
            Expanded(
              child: Text(
                pos.positionContext,
                style: const TextStyle(
                  fontWeight: FontWeight.bold,
                  fontSize: 18,
                ),
              ),
            ),
            if (onEdit != null)
              IconButton(
                onPressed: onEdit,
                icon: const Icon(Icons.edit, size: 16),
                tooltip: 'Edit this tactic',
                visualDensity: VisualDensity.compact,
                constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
                padding: EdgeInsets.zero,
              ),
          ],
        ),
        const SizedBox(height: 12),
        Text(
          'Game: ${pos.gameWhite} vs ${pos.gameBlack}',
          style: const TextStyle(fontSize: 14),
          // Names vary per puzzle; keep to one line so the header height (and
          // everything below it) doesn't jump when a longer pairing wraps.
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
        ),
        if (pos.userMove.isNotEmpty) ...[
          const SizedBox(height: 8),
          Text(
            'You played: ${pos.userMove}${pos.mistakeType}',
            style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
          ),
          // Always reserve the "Allows" line's height, even when no opponent
          // reply was stored, so puzzles with and without one keep the same
          // header height and the buttons below never shift on Next/Previous.
          Visibility(
            visible: pos.opponentBestResponse.isNotEmpty,
            maintainSize: true,
            maintainAnimation: true,
            maintainState: true,
            child: Text(
              'Allows: ${pos.opponentBestResponse}',
              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
            ),
          ),
        ],
        const SizedBox(height: 4),
        // Single-move tactics show nothing here, but the line's height is
        // always reserved so the panel doesn't bounce on Next/Previous.
        Visibility(
          visible: moveCount > 1,
          maintainSize: true,
          maintainAnimation: true,
          maintainState: true,
          child: Text(
            '$moveCount-move tactic',
            style: const TextStyle(fontSize: 14),
          ),
        ),
      ],
    );
  }
}
