/// Invariant (property) tests for the opening-tree data structures.
///
/// These assert *laws* that must hold for every input, not the output of any
/// particular input: merging games is idempotent in shape and linear in
/// stats, it does not depend on the order the games arrived in, every move in
/// a file is reachable in the tree, a path navigated to reads back as itself,
/// and two builds of the same input are identical down to child order.
///
/// Inputs are real games: every move is generated by dartchess from the legal
/// moves of the position, so the trees here are shaped like the ones the app
/// builds. Loops are seeded, so a failure reproduces from the seed in the
/// reason string.
library;

import 'dart:math';

import 'package:chess_auto_prep/models/opening_tree.dart';
import 'package:chess_auto_prep/utils/fen_utils.dart';
import 'package:dartchess/dartchess.dart';
import 'package:flutter_test/flutter_test.dart';

import 'tree_property_support.dart';

/// The results a generated game can carry. `*` makes the builder fold the
/// game's variations in as separate lines (course/repertoire behaviour);
/// a scored game is walked mainline-only.
const _results = ['*', '*', '1-0', '0-1', '1/2-1/2'];

/// A seeded batch of games, each a legal game tree with variations.
List<String> _randomGames(int seed, {int? count}) {
  final rng = Random(seed);
  final games = <String>[];
  final n = count ?? 1 + rng.nextInt(4);
  for (var i = 0; i < n; i++) {
    final moves = randomGameTree(
      rng,
      Chess.initial,
      maxDepth: 3 + rng.nextInt(5),
      branch: 0.5,
    );
    games.add(pgnOf(moves, result: _results[rng.nextInt(_results.length)]));
  }
  return games;
}

/// How many distinct lines a PGN game holds (its game tree's leaves) — the
/// number of times the builder should count it at the root.
int _lineCount(PgnGame<PgnNodeData> game) {
  var leaves = 0;
  void walk(PgnNode<PgnNodeData> node) {
    if (node.children.isEmpty) {
      leaves++;
      return;
    }
    for (final child in node.children) {
      walk(child);
    }
  }

  walk(game.moves);
  return leaves;
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('determinism', () {
    test('the same games build the same tree, down to child order', () {
      for (var seed = 0; seed < 20; seed++) {
        final games = _randomGames(seed);
        expect(
          dumpTree(treeFrom(games)),
          dumpTree(treeFrom(games)),
          reason: 'seed $seed: two builds of one input disagree',
        );
      }
    });

    test('a rebuild reproduces the FEN index and the sorted child order', () {
      for (var seed = 0; seed < 12; seed++) {
        final games = _randomGames(seed);
        final a = treeFrom(games);
        final b = treeFrom(games);
        expect(
          a.fenToNodes.keys.toList(),
          b.fenToNodes.keys.toList(),
          reason: 'seed $seed: FEN index keys differ',
        );
        final nodesA = allNodes(a);
        final nodesB = allNodes(b);
        expect(nodesA.length, nodesB.length, reason: 'seed $seed: node count');
        for (var i = 0; i < nodesA.length; i++) {
          expect(
            nodesA[i].sortedChildren.map((c) => c.move).toList(),
            nodesB[i].sortedChildren.map((c) => c.move).toList(),
            reason: 'seed $seed: sortedChildren differ at ${nodesA[i]}',
          );
        }
      }
    });

    test('sortedChildren never goes stale as games are folded in', () {
      for (var seed = 0; seed < 20; seed++) {
        final games = _randomGames(seed, count: 4);
        final tree = OpeningTree();
        for (final game in games) {
          foldGame(tree, game);
          // Read the cache everywhere, so a later fold has something to
          // invalidate; a stale cache would survive to the check below.
          for (final node in allNodes(tree)) {
            expect(node.sortedChildren.length, node.children.length);
          }
        }
        for (final node in allNodes(tree)) {
          final expected = node.children.values.toList()
            ..sort((a, b) => b.gamesPlayed.compareTo(a.gamesPlayed));
          expect(
            node.sortedChildren.map((c) => c.gamesPlayed).toList(),
            expected.map((c) => c.gamesPlayed).toList(),
            reason: 'seed $seed: stale sortedChildren at ${node.getMovePath()}',
          );
        }
      }
    });
  });

  group('merge', () {
    test('folding the same games twice leaves the shape unchanged', () {
      for (var seed = 0; seed < 16; seed++) {
        final games = _randomGames(seed);
        expect(
          dumpShape(treeFrom([...games, ...games])),
          dumpShape(treeFrom(games)),
          reason: 'seed $seed: a second fold of the same games changed shape',
        );
      }
    });

    test('folding the same games twice doubles every count', () {
      for (var seed = 0; seed < 16; seed++) {
        final games = _randomGames(seed);
        final once = allNodes(treeFrom(games));
        final twice = allNodes(treeFrom([...games, ...games]));
        expect(twice.length, once.length, reason: 'seed $seed: node count');
        for (var i = 0; i < once.length; i++) {
          final path = once[i].getMovePath();
          expect(
            [
              twice[i].gamesPlayed,
              twice[i].wins,
              twice[i].draws,
              twice[i].losses,
            ],
            [
              2 * once[i].gamesPlayed,
              2 * once[i].wins,
              2 * once[i].draws,
              2 * once[i].losses,
            ],
            reason: 'seed $seed: counts not doubled at $path',
          );
        }
      }
    });

    test('the order games are folded in does not change the tree', () {
      for (var seed = 0; seed < 20; seed++) {
        final games = _randomGames(seed, count: 3);
        final forward = treeFrom(games);
        final backward = treeFrom(games.reversed);
        expect(
          dumpTree(backward, ordered: false),
          dumpTree(forward, ordered: false),
          reason: 'seed $seed: merge is order dependent',
        );
      }
    });

    test('merging games in different orders is associative', () {
      for (var seed = 0; seed < 12; seed++) {
        final games = _randomGames(seed, count: 3);
        if (games.length < 3) continue;
        // (a then b) then c  ==  a then (b then c): the tree is grown in
        // place, so associativity is the claim that the fold has no state
        // beyond the tree itself.
        final left = OpeningTree();
        foldGame(left, games[0]);
        foldGame(left, games[1]);
        foldGame(left, games[2]);
        final right = OpeningTree();
        foldGame(right, games[2]);
        foldGame(right, games[1]);
        foldGame(right, games[0]);
        expect(
          dumpTree(right, ordered: false),
          dumpTree(left, ordered: false),
          reason: 'seed $seed: regrouping the fold changed the tree',
        );
      }
    });

    test('a fold only ever adds: no path is lost and no count shrinks', () {
      for (var seed = 0; seed < 16; seed++) {
        final games = _randomGames(seed, count: 4);
        final tree = OpeningTree();
        var before = <String, int>{};
        for (final game in games) {
          foldGame(tree, game);
          final after = {
            for (final node in allNodes(tree))
              node.getMovePath().join(' '): node.gamesPlayed,
          };
          for (final entry in before.entries) {
            expect(
              after[entry.key],
              isNotNull,
              reason: 'seed $seed: path "${entry.key}" vanished after a fold',
            );
            expect(
              after[entry.key]!,
              greaterThanOrEqualTo(entry.value),
              reason: 'seed $seed: count shrank at "${entry.key}"',
            );
          }
          before = after;
        }
      }
    });
  });

  group('conservation', () {
    test('every line in a file is reachable in the tree', () {
      for (var seed = 0; seed < 20; seed++) {
        final games = _randomGames(seed);
        final tree = treeFrom(games);
        for (final pgn in games) {
          final game = PgnGame.parsePgn(pgn);
          final scored = (game.headers['Result'] ?? '*').trim() != '*';
          // Scored games are walked mainline-only by design; `*` games (a
          // course, a repertoire) fold every variation in as its own line.
          final paths = scored
              ? [game.moves.mainline().map((d) => d.san).toList()]
              : allGamePaths(game);
          for (final path in paths) {
            expect(
              tree.nodeAtPath(path),
              isNotNull,
              reason: 'seed $seed: $path is in the file but not in the tree',
            );
          }
        }
      }
    });

    test('the root counts one game per line folded in', () {
      for (var seed = 0; seed < 16; seed++) {
        final games = _randomGames(seed);
        var expected = 0;
        for (final pgn in games) {
          final game = PgnGame.parsePgn(pgn);
          expected += (game.headers['Result'] ?? '*').trim() == '*'
              ? _lineCount(game)
              : 1;
        }
        expect(
          treeFrom(games).totalGames,
          expected,
          reason: 'seed $seed: root game count does not match the lines folded',
        );
      }
    });

    test('a node is played at least as often as its children together', () {
      for (var seed = 0; seed < 20; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final childSum = node.children.values.fold<int>(
            0,
            (sum, child) => sum + child.gamesPlayed,
          );
          expect(
            node.gamesPlayed,
            greaterThanOrEqualTo(childSum),
            reason:
                'seed $seed: ${node.getMovePath()} has fewer games '
                '(${node.gamesPlayed}) than its continuations ($childSum)',
          );
        }
      }
    });

    test('results never outnumber the games they came from', () {
      for (var seed = 0; seed < 20; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          expect(
            node.wins + node.draws + node.losses,
            lessThanOrEqualTo(node.gamesPlayed),
            reason: 'seed $seed: W/D/L exceeds games at ${node.getMovePath()}',
          );
          expect(node.winRate, inInclusiveRange(0.0, 1.0));
          expect(node.hasWdl, node.wins + node.draws + node.losses > 0);
        }
      }
    });

    test('the depth cap bounds every path, and nothing shallower is cut', () {
      for (var seed = 0; seed < 12; seed++) {
        final games = _randomGames(seed);
        for (final maxDepth in const [1, 2, 4]) {
          final tree = treeFrom(games, maxDepth: maxDepth);
          for (final node in allNodes(tree)) {
            expect(
              node.getMovePath().length,
              lessThanOrEqualTo(maxDepth),
              reason: 'seed $seed: node deeper than maxDepth $maxDepth',
            );
          }
          // Everything within the cap is still there.
          final full = treeFrom(games);
          for (final node in allNodes(full)) {
            final path = node.getMovePath();
            if (path.length > maxDepth) continue;
            expect(
              tree.nodeAtPath(path),
              isNotNull,
              reason: 'seed $seed: $path lost at maxDepth $maxDepth',
            );
          }
        }
      }
    });
  });

  group('structure', () {
    test('every edge is the move it claims to be', () {
      // A child's SAN, played on its parent's position, must produce exactly
      // the child's position. (Two documented exceptions are not generated
      // here: a `--`/`Z0` null move, and a `[FEN]` chapter grafted at the
      // root — see the "known gaps" group below.)
      for (var seed = 0; seed < 20; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final parent = node.parent;
          if (parent == null) continue;
          final position = Chess.fromSetup(Setup.parseFen(parent.fen));
          final move = position.parseSan(node.move);
          expect(
            move,
            isNotNull,
            reason:
                'seed $seed: ${node.move} is illegal at '
                '${parent.getMovePath()}',
          );
          expect(
            normalizeFen(position.play(move!).fen),
            normalizeFen(node.fen),
            reason: 'seed $seed: ${node.getMovePath()} stores the wrong FEN',
          );
        }
      }
    });

    test('every node is indexed under its own position exactly once', () {
      for (var seed = 0; seed < 20; seed++) {
        final tree = treeFrom(_randomGames(seed));
        final nodes = allNodes(tree);
        for (final node in nodes) {
          final indexed = tree.fenToNodes[normalizeFen(node.fen)];
          expect(
            indexed,
            isNotNull,
            reason: 'seed $seed: ${node.getMovePath()} is not indexed',
          );
          expect(
            indexed!.where((n) => identical(n, node)).length,
            1,
            reason:
                'seed $seed: ${node.getMovePath()} is indexed '
                '${indexed.where((n) => identical(n, node)).length} times',
          );
        }
        // …and the index holds nothing else: same positions, same nodes.
        final reachable = nodes.toSet();
        for (final entry in tree.fenToNodes.entries) {
          for (final node in entry.value) {
            expect(
              normalizeFen(node.fen),
              entry.key,
              reason: 'seed $seed: node filed under a foreign FEN',
            );
            expect(
              reachable.contains(node),
              isTrue,
              reason: 'seed $seed: index holds an unreachable node',
            );
          }
        }
      }
    });

    test('parent links agree with the child maps', () {
      for (var seed = 0; seed < 12; seed++) {
        final tree = treeFrom(_randomGames(seed));
        expect(tree.root.parent, isNull);
        for (final node in allNodes(tree)) {
          for (final entry in node.children.entries) {
            expect(
              identical(entry.value.parent, node),
              isTrue,
              reason: 'seed $seed: child ${entry.key} does not point back',
            );
            expect(
              entry.value.move,
              entry.key,
              reason: 'seed $seed: child filed under a foreign SAN',
            );
          }
        }
      }
    });

    test('countDescendants counts the subtree, and grows with the cap', () {
      for (var seed = 0; seed < 12; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          var size = 0;
          void count(OpeningTreeNode n) {
            size++;
            for (final child in n.children.values) {
              count(child);
            }
          }

          count(node);
          expect(node.countDescendants(maxPly: 0), 1);
          var previous = 0;
          for (var ply = 0; ply <= 12; ply++) {
            final now = node.countDescendants(maxPly: ply);
            expect(
              now,
              greaterThanOrEqualTo(previous),
              reason: 'seed $seed: countDescendants shrank at ply $ply',
            );
            previous = now;
          }
          expect(
            previous,
            size,
            reason: 'seed $seed: countDescendants never reaches the subtree',
          );
        }
      }
    });
  });

  group('navigation round trips', () {
    test('a node is found again by its own move path', () {
      for (var seed = 0; seed < 20; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          expect(
            identical(tree.nodeAtPath(node.getMovePath()), node),
            isTrue,
            reason: 'seed $seed: nodeAtPath lost ${node.getMovePath()}',
          );
        }
      }
    });

    test('walking a path reads the same path back', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final path = node.getMovePath();
          expect(tree.syncToMoveHistory(path), isTrue, reason: 'seed $seed');
          expect(
            tree.currentMovePath,
            path,
            reason: 'seed $seed: walked path came back changed',
          );
          expect(tree.currentDepth, path.length, reason: 'seed $seed');
          expect(
            normalizeFen(tree.currentFen),
            normalizeFen(node.fen),
            reason: 'seed $seed: cursor landed on another position',
          );
          expect(tree.inBook, isTrue, reason: 'seed $seed: $path left book');
          expect(tree.canGoBack, path.isNotEmpty, reason: 'seed $seed');
        }
      }
    });

    test('syncToFens agrees with syncToMoveHistory on every book path', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final path = node.getMovePath();
          Position position = Chess.fromSetup(Setup.parseFen(tree.root.fen));
          final fens = <String>[];
          for (final san in path) {
            position = position.play(position.parseSan(san)!);
            fens.add(position.fen);
          }
          final bySan = tree.syncToMoveHistory(path);
          final sanFen = normalizeFen(tree.currentFen);
          final sanPath = tree.currentMovePath;
          final byFen = tree.syncToFens(path, fens);
          expect(byFen, bySan, reason: 'seed $seed: disagree on $path');
          expect(normalizeFen(tree.currentFen), sanFen, reason: 'seed $seed');
          expect(tree.currentMovePath, sanPath, reason: 'seed $seed');
        }
      }
    });

    test('a move and a step back cancel out', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final path = node.getMovePath();
          if (path.isEmpty) continue;
          tree.syncToMoveHistory(path);
          final fen = normalizeFen(tree.currentFen);
          expect(tree.goBack(), isTrue, reason: 'seed $seed: goBack at $path');
          expect(
            tree.currentMovePath,
            path.sublist(0, path.length - 1),
            reason: 'seed $seed: goBack did not undo one ply',
          );
          expect(
            tree.makeMove(path.last),
            isTrue,
            reason: 'seed $seed: cannot replay ${path.last} at $path',
          );
          expect(
            normalizeFen(tree.currentFen),
            fen,
            reason: 'seed $seed: move-then-back-then-move moved the board',
          );
        }
      }
    });

    test('reset and navigateToFen put the cursor in a known state', () {
      for (var seed = 0; seed < 12; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          expect(tree.navigateToFen(node.fen), isTrue, reason: 'seed $seed');
          expect(normalizeFen(tree.currentFen), normalizeFen(node.fen));
          expect(tree.inBook, isTrue);
          // The cursor's path is a real path to that position.
          expect(
            normalizeFen(tree.nodeAtPath(tree.currentMovePath)!.fen),
            normalizeFen(node.fen),
            reason: 'seed $seed: navigateToFen reported an unwalkable path',
          );
          tree.reset();
          expect(tree.currentMovePath, isEmpty);
          expect(tree.currentDepth, 0);
          expect(tree.canGoBack, isFalse);
          expect(normalizeFen(tree.currentFen), normalizeFen(tree.root.fen));
        }
      }
    });
  });

  group('continuations', () {
    test('every continuation offered is legal and lands where it says', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final position = Chess.fromSetup(Setup.parseFen(node.fen));
          final groups = tree.continuationsAt(node.fen);
          for (final group in groups) {
            final move = position.parseSan(group.move);
            expect(
              move,
              isNotNull,
              reason:
                  'seed $seed: illegal continuation ${group.move} at '
                  '${node.getMovePath()}',
            );
            expect(
              normalizeFen(position.play(move!).fen),
              normalizeFen(group.fen),
              reason: 'seed $seed: ${group.move} does not lead to its group',
            );
            tree.syncToMoveHistory(node.getMovePath());
            expect(
              tree.makeMove(group.move),
              isTrue,
              reason: 'seed $seed: offered ${group.move} but cannot play it',
            );
            expect(normalizeFen(tree.currentFen), normalizeFen(group.fen));
          }
        }
      }
    });

    test('continuations hold every move played from the position', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final played = <String>{};
          for (final twin in tree.fenToNodes[normalizeFen(node.fen)]!) {
            played.addAll(twin.children.keys);
          }
          final offered = tree
              .continuationsAt(node.fen)
              .map((g) => g.move)
              .toSet();
          expect(
            offered,
            containsAll(played),
            reason:
                'seed $seed: ${played.difference(offered)} missing at '
                '${node.getMovePath()}',
          );
          for (final san in played) {
            expect(
              tree.hasMove(node.fen, san),
              isTrue,
              reason: 'seed $seed: hasMove denies a played move',
            );
            expect(
              tree.doesMoveTranspose(node.fen, san),
              isTrue,
              reason: 'seed $seed: a played move leaves the book',
            );
            expect(
              tree.hasMoveOnPath(node.getMovePath(), san),
              isTrue,
              reason: 'seed $seed: hasMoveOnPath denies a child',
            );
          }
        }
      }
    });

    test('continuations come back most-played first, and sum consistently', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final node in allNodes(tree)) {
          final groups = tree.continuationsAt(node.fen);
          for (var i = 1; i < groups.length; i++) {
            expect(
              groups[i - 1].gamesPlayed,
              greaterThanOrEqualTo(groups[i].gamesPlayed),
              reason: 'seed $seed: continuations are not sorted',
            );
          }
          for (final group in groups) {
            expect(group.nodes, isNotEmpty);
            expect(
              group.gamesPlayed,
              group.nodes.fold<int>(0, (s, n) => s + n.gamesPlayed),
              reason: 'seed $seed: group total is not the sum of its paths',
            );
            expect(
              group.wins + group.draws + group.losses,
              lessThanOrEqualTo(group.gamesPlayed),
            );
            expect(
              group.nodes.map((n) => normalizeFen(n.fen)).toSet().length,
              1,
              reason: 'seed $seed: a group mixes positions',
            );
          }
        }
      }
    });

    test('a position not in the tree offers nothing but transpositions', () {
      // Deliberately walk somewhere the book has never been: continuations
      // must then be exactly the legal moves that land back in the book.
      final rng = Random(99);
      for (var seed = 0; seed < 8; seed++) {
        final tree = treeFrom(_randomGames(seed));
        final offBook = randomLine(rng, maxPlies: 6);
        Position pos = Chess.fromSetup(Setup.parseFen(tree.root.fen));
        var legal = true;
        for (final san in offBook) {
          final move = pos.parseSan(san);
          if (move == null) {
            legal = false;
            break;
          }
          pos = pos.play(move);
        }
        if (!legal) continue;
        if (tree.fenToNodes.containsKey(normalizeFen(pos.fen))) continue;
        for (final group in tree.continuationsAt(pos.fen)) {
          expect(
            group.viaTransposition,
            isTrue,
            reason: 'seed $seed: an off-book position offered a book move',
          );
          expect(
            tree.fenToNodes.containsKey(normalizeFen(group.fen)),
            isTrue,
            reason: 'seed $seed: a transposition that leaves the book',
          );
        }
      }
    });
  });

  group('transpositions', () {
    // Every interleaving of these move sets is legal and reaches the same
    // position, so the tree gets one position with many concrete paths.
    test('all move orders converge on one indexed position', () {
      for (var seed = 0; seed < 16; seed++) {
        final rng = Random(seed);
        final orders = <List<String>>[];
        for (var i = 0; i < 2 + rng.nextInt(4); i++) {
          orders.add(randomTransposingOrder(rng));
        }
        final tree = treeFrom(orders.map((o) => pgnOfLine(o, result: '1-0')));

        Position position = Chess.initial;
        for (final san in orders.first) {
          final move = position.parseSan(san);
          expect(move, isNotNull, reason: 'generated order is illegal');
          position = position.play(move!);
        }
        final target = normalizeFen(position.fen);
        final distinctOrders = orders.map((o) => o.join(' ')).toSet();

        final nodes = tree.fenToNodes[target];
        expect(nodes, isNotNull, reason: 'seed $seed: target not indexed');
        expect(
          nodes!.length,
          distinctOrders.length,
          reason: 'seed $seed: one node per distinct move order expected',
        );
        final group = PositionGroup(nodes);
        expect(
          group.gamesPlayed,
          orders.length,
          reason: 'seed $seed: transposing paths do not sum to the games',
        );
        expect(group.wins + group.draws + group.losses, orders.length);
        for (final order in distinctOrders) {
          final path = order.split(' ');
          expect(
            normalizeFen(tree.nodeAtPath(path)!.fen),
            target,
            reason: 'seed $seed: $path does not reach the shared position',
          );
          expect(tree.syncToMoveHistory(path), isTrue, reason: 'seed $seed');
          expect(normalizeFen(tree.currentFen), target);
          expect(tree.currentMovePath, path);
        }
      }
    });

    test('a move order nobody played still finds the position', () {
      // The whole point of the FEN index: the book is a set of positions, not
      // a set of move orders. Only orders whose every intermediate position
      // is also in the book are claimed here — a walk that leaves the book in
      // the middle is off-book by design.
      for (var seed = 0; seed < 16; seed++) {
        final rng = Random(1000 + seed);
        final orders = [
          for (var i = 0; i < 4; i++) randomTransposingOrder(rng),
        ];
        final tree = treeFrom(orders.map((o) => pgnOfLine(o)));
        final hybrid = randomTransposingOrder(rng);
        if (orders.any((o) => o.join(' ') == hybrid.join(' '))) continue;

        expect(
          tree.syncToMoveHistory(hybrid),
          isTrue,
          reason: 'seed $seed: $hybrid lost the book',
        );
        expect(tree.currentMovePath, hybrid);
        expect(
          normalizeFen(tree.currentFen),
          normalizeFen(tree.nodeAtPath(orders.first)!.fen),
          reason: 'seed $seed: the hybrid order landed elsewhere',
        );
      }
    });

    test('a group sums its paths and merges their continuations', () {
      for (var seed = 0; seed < 12; seed++) {
        final rng = Random(2000 + seed);
        final orders = [
          for (var i = 0; i < 3; i++) randomTransposingOrder(rng),
        ];
        // Give each order a different continuation, so the merge is visible.
        const differentContinuations = ['Bg2', 'Qb3', 'h3'];
        final games = <String>[];
        for (var i = 0; i < orders.length; i++) {
          games.add(pgnOfLine([...orders[i], differentContinuations[i]]));
        }
        final tree = treeFrom(games);
        for (final node in allNodes(tree)) {
          final group = tree.groupFor(node);
          expect(group.nodes.map((n) => normalizeFen(n.fen)).toSet(), {
            normalizeFen(node.fen),
          }, reason: 'seed $seed: groupFor mixed positions');
          expect(
            group.gamesPlayed,
            greaterThanOrEqualTo(node.gamesPlayed),
            reason: 'seed $seed: a group counts less than one of its paths',
          );
          final merged = group.children.fold<int>(
            0,
            (sum, child) => sum + child.gamesPlayed,
          );
          expect(
            merged,
            lessThanOrEqualTo(group.gamesPlayed),
            reason: 'seed $seed: merged continuations outnumber the games',
          );
        }
      }
    });

    test('reach never grows along a line, and a group never loses reach', () {
      for (var seed = 0; seed < 12; seed++) {
        final tree = treeFrom(_randomGames(seed));
        for (final white in const [true, false]) {
          expect(
            tree.root.reachEstimate(protagonistIsWhite: white).probability,
            1.0,
            reason: 'seed $seed: the start position is not certain',
          );
          for (final node in allNodes(tree)) {
            final here = node.reachEstimate(protagonistIsWhite: white);
            expect(here.probability, inInclusiveRange(0.0, 1.0));
            expect(here.decisionPoints, greaterThanOrEqualTo(0));
            final parent = node.parent;
            if (parent != null) {
              final above = parent.reachEstimate(protagonistIsWhite: white);
              expect(
                here.probability,
                lessThanOrEqualTo(above.probability + 1e-9),
                reason: 'seed $seed: reach grew at ${node.getMovePath()}',
              );
              expect(
                here.decisionPoints,
                greaterThanOrEqualTo(above.decisionPoints),
                reason: 'seed $seed: decisions un-counted down a line',
              );
            }
            final group = tree
                .groupFor(node)
                .reachEstimate(protagonistIsWhite: white);
            expect(
              group.probability,
              greaterThanOrEqualTo(here.probability - 1e-9),
              reason: 'seed $seed: summing paths lost reach',
            );
            expect(group.probability, inInclusiveRange(0.0, 1.0));
          }
        }
      }
    });
  });

  group('isolate transfer', () {
    test('a tree survives the round trip through its transfer JSON', () {
      for (var seed = 0; seed < 16; seed++) {
        final tree = treeFrom(_randomGames(seed));
        final copy = OpeningTree.fromTransferJson(tree.toTransferJson());
        expect(
          dumpTree(copy),
          dumpTree(tree),
          reason: 'seed $seed: the transferred tree is not the same tree',
        );
        expect(allNodes(copy).length, allNodes(tree).length);
        // The FEN index must hold the same positions and the same paths.
        // Only the *order* of the paths under one FEN is not claimed: the
        // sender indexes in walk order, the receiver in breadth-first order.
        expect(
          copy.fenToNodes.keys.toSet(),
          tree.fenToNodes.keys.toSet(),
          reason: 'seed $seed: positions lost in transfer',
        );
        for (final key in tree.fenToNodes.keys) {
          expect(
            copy.fenToNodes[key]!.map((n) => n.getMovePath().join(' ')).toSet(),
            tree.fenToNodes[key]!.map((n) => n.getMovePath().join(' ')).toSet(),
            reason: 'seed $seed: paths to $key changed in transfer',
          );
        }
      }
    });

    test('the transferred tree navigates like the original', () {
      for (var seed = 0; seed < 12; seed++) {
        final tree = treeFrom(_randomGames(seed));
        final copy = OpeningTree.fromTransferJson(tree.toTransferJson());
        for (final node in allNodes(tree)) {
          final path = node.getMovePath();
          expect(copy.syncToMoveHistory(path), tree.syncToMoveHistory(path));
          expect(
            normalizeFen(copy.currentFen),
            normalizeFen(tree.currentFen),
            reason: 'seed $seed: the copy walks $path elsewhere',
          );
          expect(
            copy.continuationsAt(node.fen).map((g) => g.move).toSet(),
            tree.continuationsAt(node.fen).map((g) => g.move).toSet(),
            reason: 'seed $seed: continuations differ after transfer',
          );
        }
      }
    });
  });

  group('appending lines', () {
    test('an appended line is a walkable, indexed, consistent path', () {
      for (var seed = 0; seed < 16; seed++) {
        final rng = Random(3000 + seed);
        final tree = treeFrom(_randomGames(seed));
        for (var i = 0; i < 3; i++) {
          final line = randomLine(rng, maxPlies: 5);
          tree.appendLine(line);
          expect(
            tree.nodeAtPath(line),
            isNotNull,
            reason: 'seed $seed: appended $line is not in the tree',
          );
        }
        for (final node in allNodes(tree)) {
          final parent = node.parent;
          if (parent == null) continue;
          final position = Chess.fromSetup(Setup.parseFen(parent.fen));
          final move = position.parseSan(node.move);
          expect(
            move,
            isNotNull,
            reason: 'seed $seed: appending broke an edge',
          );
          expect(
            normalizeFen(position.play(move!).fen),
            normalizeFen(node.fen),
          );
          expect(
            tree.fenToNodes[normalizeFen(node.fen)],
            contains(node),
            reason: 'seed $seed: an appended node is unindexed',
          );
        }
      }
    });
  });

  group('grafted [FEN] chapters', () {
    // A chapter that starts from a `[FEN]` header is anchored on the node
    // standing at that position, and grafted at the root when no node does.
    const chapterFen =
        'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4';
    const mainGame = '''
[Event "Main"]
[White "Me"]
[Black "Opponent"]
[Result "*"]

1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6 *
''';
    const chapter =
        '''
[Event "Chapter"]
[White "Me"]
[Black "Opponent"]
[Result "*"]
[FEN "$chapterFen"]

4. Ng5 d5 *
''';

    test('a chapter is folded into the line that reaches its position', () {
      final tree = treeFrom([mainGame, chapter]);
      expect(
        tree.nodeAtPath(['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5']),
        isNotNull,
        reason: 'the chapter did not join the line that reaches its position',
      );
      expect(tree.root.children.keys, [
        'e4',
      ], reason: 'the chapter was grafted even though its position was known');
    });

    test('a graft never merges into an unrelated line with the same SAN', () {
      // 1.d4 from the start and 4.d4 from the chapter share a SAN but not a
      // position: folding them together must not pool their statistics.
      const standard = '''
[Event "Standard"]
[White "Me"]
[Black "Opponent"]
[Result "*"]

1. d4 d5 *
''';
      const collidingChapter =
          '''
[Event "Chapter"]
[White "Me"]
[Black "Opponent"]
[Result "*"]
[FEN "$chapterFen"]

4. d4 exd4 *
''';
      final tree = treeFrom([standard, collidingChapter]);
      final d4 = tree.root.children['d4']!;
      Position start = Chess.initial;
      expect(
        normalizeFen(d4.fen),
        normalizeFen(start.play(start.parseSan('d4')!).fen),
        reason: 'the chapter was folded into the standard-start line',
      );
      expect(
        d4.gamesPlayed,
        1,
        reason: 'the chapter contributed statistics to an unrelated line',
      );
      expect(d4.children.keys, ['d5']);
    });

    test('the order a batch arrives in does not change the tree', () {
      // The viewer rebuilds its tree from the *sorted, filtered* game list,
      // so folding order is whatever the user last sorted by.
      final expected = dumpTree(treeFrom([mainGame, chapter]), ordered: false);
      expect(
        dumpTree(treeFrom([chapter, mainGame]), ordered: false),
        expected,
        reason: 'a chapter folded before its own line built a different tree',
      );
    });

    test('a chapter anchored inside another chapter lands in any order', () {
      // deepChapter starts where chapter's own line ends, so it can only
      // anchor after chapter has been folded — whatever order they arrive in.
      const deepFen =
          'r1bqkb1r/ppp2ppp/2n2n2/3pp1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 0 5';
      const deepChapter = '''
[Event "Deep chapter"]
[White "Me"]
[Black "Opponent"]
[Result "*"]
[FEN "$deepFen"]

5. exd5 Na5 *
''';
      final line = ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5'];
      final orders = [
        [mainGame, chapter, deepChapter],
        [deepChapter, chapter, mainGame],
        [chapter, deepChapter, mainGame],
        [deepChapter, mainGame, chapter],
      ];
      final expected = dumpTree(treeFrom(orders.first), ordered: false);
      for (final order in orders) {
        final tree = treeFrom(order);
        expect(
          tree.nodeAtPath([...line, 'exd5']),
          isNotNull,
          reason: 'a chapter of a chapter did not anchor',
        );
        expect(
          tree.root.children.keys,
          ['e4'],
          reason: 'something was grafted at the root',
        );
        expect(
          dumpTree(tree, ordered: false),
          expected,
          reason: 'chapter order changed the tree',
        );
      }
    });

    test('a chapter nothing reaches is still grafted, and only that one', () {
      // Nothing in this batch reaches the chapter's start position, so it is
      // grafted at the root — visible rather than dropped, which is the whole
      // point of the graft. Order still does not matter.
      const unrelated = '''
[Event "Unrelated"]
[White "Me"]
[Black "Opponent"]
[Result "*"]

1. d4 d5 *
''';
      final forward = treeFrom([unrelated, chapter]);
      final backward = treeFrom([chapter, unrelated]);
      expect(
        dumpTree(backward, ordered: false),
        dumpTree(forward, ordered: false),
      );
      expect(forward.root.children.keys.toSet(), {'d4', 'Ng5'});
      expect(
        forward.nodeAtPath(['Ng5', 'd5']),
        isNotNull,
        reason: 'an unanchorable chapter must still be reachable',
      );
    });
  });

  group('known gaps (documented, not fixed)', () {
    // Asserts the law as it *should* hold. Skipped because the production
    // code does not satisfy it today; see the report that came with this
    // file. Un-skip when the behaviour is fixed.

    test(
      'every edge in the tree is a legal move at its parent',
      () {
        // `1. e4 -- 2. d4`: the null move passes the turn without a node, so
        // `d4` is hung under the position after 1.e4, where it is Black to move
        // and `d4` is not a legal move at all.
        final tree = treeFrom([
          pgnOfLine(['e4', '--', 'd4']),
        ]);
        final e4 = tree.root.children['e4']!;
        final position = Chess.fromSetup(Setup.parseFen(e4.fen));
        expect(
          e4.children.keys.every((san) => position.parseSan(san) != null),
          isTrue,
          reason: 'the tree offers a move that cannot be played',
        );
      },
      skip:
          'BUG, deliberately left standing: a null move (--, Z0) mid-line '
          'hangs the next move on the position before it, so the edge is '
          'illegal at its parent and continuationsAt offers a move the board '
          'refuses. Fixing it is a product decision, not a slip — two tests '
          'in test/services/pgn_tree_core_test.dart ("ChessBase Z0 passes the '
          'turn without creating a tree node" and "promotes a Chessable dummy '
          'intro onto the mainline") require exactly this shape, because it '
          'is how a Chessable intro chapter shows its White setup line. The '
          'only two repairs are a "--" node in the move list or dropping the '
          'rest of such a chapter; both change what the app shows.',
    );
  });
}
